{{- $fullName := include "project-template.fullname" . -}}
{{- $namespace := include "project-template.namespace" . -}}
{{- $labels := include "project-template.labels" . -}}
{{- $buildtype := .Values.buildtype -}}
{{- $hasCustomDomains := contains ("TRUE") (include "project-template.filteredcustomdomains" .) -}}
{{- if and (.Values.customhosts) (.Values.servePublicly) ($hasCustomDomains) -}}
{{range .Values.customhosts }}
{{- if eq .buildtype $buildtype -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ $namespace }}
  name: {{ printf "%s-%s-custom" $fullName .host | replace "/" "-" | replace "." "-" }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # CNAME records must exist for all custom hostnames
  tls:
    - hosts:
        {{ if .tls -}}
        - {{ .host | quote }}
      secretName: {{ .host }}
        {{ end }}

  rules:
    - host: {{ .host | quote }}
      http:
        paths: {{ range .paths }}
          - path: {{ .path }}
            backend:
              servicePort: {{ .port }}
              serviceName: {{ $fullName }}
          {{ end }}
{{ end }}
{{ end }}
{{ end }}