{{- $fullName := include "project-template.fullname" . -}}
{{- $namespace := include "project-template.namespace" . -}}
{{- $labels := include "project-template.labels" . -}}
{{- $noIndexingAndNoFollow := include "project-template.noindexandnofollow" . -}}
{{- $buildtype := .Values.buildtype -}}
{{- $maxBodySize := .Values.maxBodySize -}}
{{- $hasCustomDomains := contains ("TRUE") (include "project-template.filteredcustomdomains" .) -}}

{{- $noIndexingAnnotation := false -}}
{{- if .Values.noIndexingOnBuildtype -}}
{{ range $val := .Values.noIndexingOnBuildtype }}
{{- if eq $val $buildtype -}}
{{- $noIndexingAnnotation = true -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- if and (.Values.customhosts) (.Values.servePublicly) ($hasCustomDomains) -}}
{{range .Values.customhosts }}
{{- if eq .buildtype $buildtype -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ $namespace }}
  name: {{ printf "%s-%s-custom" $fullName .host | replace "/" "-" | replace "." "-" }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
  {{- if $noIndexingAnnotation -}}
    {{- $noIndexingAndNoFollow | nindent 4 -}}
  {{- end -}}
{{- if $maxBodySize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ $maxBodySize | quote }}
{{- end }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # CNAME records must exist for all custom hostnames
  tls:
    - hosts:
        {{- if .tls }}
        - {{ .host | quote }}
      secretName: {{ .host }}
        {{- end }}

  rules:
    - host: {{ .host | quote }}
      http:
        paths: {{ range .paths }}
          - path: {{ .path }}
            backend:
              servicePort: {{ .port }}
              serviceName: {{ $fullName }}
          {{ end }}
{{ end }}
{{ end }}
{{ end }}