{{- if not .Values.cronjob -}}
{{- if .Values.servePublicly -}}
  {{- $buildtype := .Values.buildtype -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ include "project-template.namespace" . }}
  name: {{ include "project-template.fullname" . }}
  labels:
    {{- include "project-template.labels" . | nindent 4 }}
  annotations:
{{- if .Values.connectTimeout}}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.connectTimeout | quote }}
{{- end }}
{{- if .Values.sendTimeout}}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.sendTimeout | quote }}
{{- end }}
{{- if .Values.readTimeout}}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.readTimeout | quote }}
{{- end }}
{{- if .Values.maxBodySize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.maxBodySize | quote }}
{{- end }}
{{- if .Values.proxyBuffer }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: {{ .Values.proxyBuffer | quote }}
{{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ include "project-template.domain" . }}
  rules:
    - host: {{ include "project-template.domain" . }}
      http:
        paths:
          - path: "/"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ include "project-template.fullname" . }}
                port:
                  number: 80
{{ end }}
{{ end }}
