{{- if .Values.servePublicly -}}
  {{- $buildtype := .Values.buildtype -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ include "project-template.namespace" . }}
  name: {{ include "project-template.fullname" . }}
  labels:
    {{- include "project-template.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.noIndexingOnBuildtype -}}
    {{range $val := .Values.noIndexingOnBuildtype}}
    {{- if eq $val $buildtype -}}
      {{- include "project-template.noindexandnofollow" . | nindent 4 -}}
    {{- end -}}
    {{- end -}}
    {{- end -}}
{{- if .Values.maxBodySize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.maxBodySize | quote }}
{{- end }}
{{- if .Values.proxyBuffer }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: {{ .Values.proxyBuffer | quote }}
{{- end }}
spec:
  tls:
    - hosts:
        - {{ include "project-template.domain" . }}
  rules:
    - host: {{ include "project-template.domain" . }}
      http:
        paths:
          - path: "/"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ include "project-template.fullname" . }}
                port:
                  number: 80
{{ end }}
