{{ $contact := .Values.contact.name }}
{{ $namespace := include "project-template.namespace" . }}
{{ $labels := include "project-template.labels" . }}
{{- if .Values.persistentVolumes -}}
  {{ range .Values.persistentVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $namespace }}
  name: {{ .name }}-folder
  labels:
    {{ $labels | nindent 4 }}
spec:
  accessModes:
    # SysEleven OpenStack does not support ReadWriteMany
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .storageSize }}Gi
---
  {{ end }}
{{ end }}