apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: {{ include "project-template.namespace" . }}
  name: {{ include "project-template.fullname" . }}
  labels:
    {{- include "project-template.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "project-template.selectorLabels" . | nindent 6 }}
