
{{- $labels := include "user-creation.labels" . | nindent 4 }}
{{- range .Values.projects }}
{{ $namespace := .name | replace "/" "-"}}
{{ $name := .name | replace "/" "-" }}
{{ $username := printf "%s-user" $name }}
{{ $rolename := printf "%s-RoleName" $username }}

# We loop over all projects, specified in the values.yaml

---
# Create a namespace for the current project
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  labels:
    {{ $labels }}


---
# Create a default LimitRange for this namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ $namespace }}-limit-range
  namespace: {{ $namespace }}
  labels:
    {{ $labels }}
spec:
  limits:
  # default limits per Pod
  # using 1:4 ratio as default
  - default:
      cpu: 125m
      memory: 512Mi
    defaultRequest:
      cpu: 10m
      memory: 32Mi
    type: Container

---
# Resource Quotas per user, e.g. namespace
# https://kubernetes.io/docs/tasks/administer-cluster/quota-api-object/
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ $namespace }}-quota
  namespace: {{ $namespace }}
  labels:
    {{ $labels }}
spec:
  hard:
    # request can never be greater than the limit
    # => a malicous user can not set the request to e.g. 15GB while conforming to a set limit of 2GB
    limits.cpu: {{ .cpuLimit }}
    limits.memory: {{ .ramLimit }}

---
# DEFAULT USER - This user should be used in the CI environment variables
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $username }}
  namespace: {{ $namespace }}
  labels:
    {{ $labels }}

---
# Bind the role to the created ServiceAccount
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ $username }}-RoleBinding
  namespace: {{ $namespace }}
  labels:
    {{ $labels }}
subjects:
- kind: ServiceAccount
  name: {{ $username }}
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $rolename }}
  
---
# We need a role with the right permissions for this namespace
# Source: https://github.com/syseleven/golem-workshop/blob/master/26-rbac/simon-dev-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $rolename }}
  namespace: {{ $namespace }}
  labels:
    {{ $labels }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  - secrets
  - services/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - serviceaccounts
  - services
  - services/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

{{- end }}
